-- DATABASE
CREATE DATABASE cadastro_pessoa;

-- TABELA DE CADASTRO DE PESSOAS
CREATE TABLE PESSOA (
    ID_PES VARCHAR(64) NOT NULL
    ,NUM_DOCM_PES VARCHAR(11) NOT NULL
    ,NOM_PES VARCHAR(200) NOT NULL
    ,NUM_IDAE_PES INT
    ,PRIMARY KEY (ID_PES)
);

-- TABELA DE CADASTRO DE ENDEREÇO
CREATE TABLE ENDERECO (
    ID_END_PES VARCHAR (64) NOT NULL
    ,ID_PES VARCHAR(64) NOT NULL
    ,NOM_LOGD_END VARCHAR(200) NOT NULL
    ,NUM_LOGD_END INT NOT NULL
    ,DES_COMP_END VARCHAR(50)
    ,NOM_BAIR_END VARCHAR(100) NOT NULL
    ,NOM_CIDA_END VARCHAR(100) NOT NULL
    ,NOM_PAIS_END VARCHAR(50) NOT NULL
    ,COD_POST_END VARCHAR(15) NOT NULL
    ,PRIMARY KEY (ID_PES)
    ,FOREIGN KEY (ID_PES) REFERENCES PESSOA(ID_PES)
);

-- TABELA DE TELEFONES DE PESSOAS
CREATE TABLE TELEFONE (
    ID_TEL_PES VARCHAR(64) NOT NULL
    ,ID_PES VARCHAR(64) NOT NULL
    ,COD_DDI_TEL CHAR(3) NOT NULL
    ,COD_DDD_TEL CHAR(3) NOT NULL
    ,NUM_TEL_PES BIGINT NOT NULL
    ,IDTO_CATG_TEL CHAR(1) NOT NULL
    ,PRIMARY KEY (ID_TEL_PES)
    ,FOREIGN KEY (ID_PES) REFERENCES PESSOA(ID_PES)
);

-- TABELA DE EMAIL DE PESSOAS
CREATE TABLE EMAIL (
    ID_EMAL_PES VARCHAR(64) NOT NULL
    ,ID_PES VARCHAR(64) NOT NULL
    ,DES_EMAL_PES VARCHAR(30) NOT NULL
    ,PRIMARY KEY (ID_EMAL_PES)
    ,FOREIGN KEY (ID_PES) REFERENCES PESSOA(ID_PES)
);